[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"

[[main]]
  name = "About"
  url = "/docs/book/about/"
  weight = 10

[[main]]
  name = "Your Purpose"
  url = "/docs/book/your-purpose/"
  weight = 20

[[main]]
  name = "Your Purpose"
  url = "/docs/book/your-purpose/"
  weight = 30

[[main]]
  name = "Your Purpose"
  url = "/docs/book/your-purpose/"
  weight = 40

[[main]]
  name = "Your Identity"
  url = "/docs/book/your-identity/"
  weight = 50

[[main]]
  name = "Who is Jesus?"
  url = "/docs/book/who-is-jesus-christ/"
  weight = 60

 [[social]]
   name = "Instagram"
   pre = ""
   url = "https://www.instagram.com/godspace.io/"
   post = "v0.1.0"
   weight = 10

 [[social]]
   name = "Godspace eChurch, Social Network"
   pre = ""
   url = "https://godspace.io"
   post = "v0.1.0"
   weight = 11


# [[social]]
#   name = "TikTok"
#   pre = ""
#   url = "https://www.tiktok.com/@chatswithjesus"
#   post = "v0.1.0"
#   weight = 10

# [[social]]
#   name = "Rumble"
#   pre = ""
#   url = "https://rumble.com/user/chatswithjesus"
#   post = "v0.1.0"
#   weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
